name: .NET Core CI/CD

on:
  push:
    branches: [ "main" ]
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Add button for manual run on GitHub

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install Playwright Browsers
      run: |
        dotnet build PricePulse.Tests/PricePulse.Tests.csproj
        pwsh PricePulse.Tests/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal